---
title: Citizen Analytics - CITYBLE project
author: ''
date: '2025-12-04'
slug: citizen-analytics-cityble-project
categories: []
tags: []
---

This post concerns the PRIN project called CITYBLE that I coordinated.
The project's partners are the [University of Ferrara](https://www.unife.it/it), [University of Milan](https://www.unimi.it/it) and [University of Salento](https://www.unisalento.it/) and the supporting organisations and institutions are [CDS](https://www.cdscultura.com/), [Comune di Ferrara](https://www.comune.ferrara.it/), [Comune di Bergamo](https://www.comune.bergamo.it/) e [Comune di Lecce](https://www.comune.lecce.it/).

The project full title is CITYBLE - Developing Two-Sided Citizen Analytics for the Sustainable Digital Society.

The project idea was rooted in the awareness that the emergence of a global digital society is challenging the ways in which governments interact with their communities. The new socio-economic trends are thus spurring a need to look at the interrelated socio-economic, environmental, and psychological factors that contribute to an individual and to the society’s well-being.

Drawing on that CITYBLE had two objectives. 

On the one hand, to develop a citizen analytics system, an analysis platform that integrates data provided by citizens and public indicators to measure and improve urban and organizational well-being; on the other hand, to lay the foundations for a participatory digital welfare system, in which collective knowledge becomes a lever for more
targeted and inclusive public policies.

The results of the research activities can be synthesized as follows.

At first, it has been shown that Citizen Science (CS) in Europe has experienced significant growth over the last twenty years, but remains heavily concentrated on environmental and technological areas, with little emphasis on social dimensions and well-being.

Focusing on the last areas, the research conducted has systematized knowledge on social well-being within the domain of sustainability, identifying measurable and comparable indicators that can be used to construct a future sustainable well-being index. One of the most significant theoretical contributions of the research project is the development of an
extended concept of social well-being, which combines individual, organizational, and social dimensions. 

Lastly, it has been created a detailed technical documentation that makes the developed analytical pipelines replicable,
contributing to the construction of a shared methodological heritage in the scientific community dealing with CS and digital sustainability. On that basis, the guidelines and best practices highlighted by the study were incorporated into the design of the prototype platform itself, through intuitive interfaces, accessible visualizations,
and feedback mechanisms that make the process of collecting, processing, and using data
produced by citizens transparent and usable by citizens themselves, practitioners and policy makers.

